### ISSUE TITLE
Hierarchy commands should auto-expand the top-level node

### ISSUE THREAD

**Issue by RedBeard0531** [m-pilia/vim-ccls#12]
The hierarchy commands start with a top-level node indicating where the command was initiated from. In basically call cases, it would be useful to expand at least the first layer, since any user would need to open that to get info they don't already have.

For member hierarchy, it might be worth just expanding recursively all direct members (ie not pointers or references), although I'm not sure if it is worth expanding stuff in `std::` or other lib namespaces, so it isn't as obvious that it is desirable to auto-open more than the first layer.

**Comment by m-pilia** [comment]
Hi!
This is a good idea.
