### ISSUE TITLE
CclsMemberFunctions & CclsMemberTypes

### ISSUE THREAD

**Issue by lanza** [m-pilia/vim-ccls#31]
CCLS offers the `$ccls/member` message with a parameter `kind` and values `2`, `3`, and `4` representing types, functions and variables. You currently have `CclsMembers` only getting vars. I think it would be useful to have this expanded to the other 2 permutations.

**Comment by lanza** [comment]
Added in two PRs.

**Comment by m-pilia** [comment]
Nice, thanks! I will have a look at them soon!
