### ISSUE TITLE
commands in this plugin will invalidate hlsearch in vim

### ISSUE THREAD

**Issue by simonjoylet** [m-pilia/vim-ccls#35]

**Comment by simonjoylet** [comment]
I work around by delete "setlocal nohlsearch" in tree.vim. 
I'm not not sure if it's a bug of the plugin or the vim.
![image](https://user-images.githubusercontent.com/5274450/98757151-dbbe0800-2406-11eb-94b7-ab4c5a58685e.png)

**Comment by m-pilia** [comment]
Hi @simonjoylet, thanks for creating this issue. I fixed the plugin to avoid changing the hlsearch option (that is global and cannot be set locally).
