### ISSUE TITLE
question: what is the difference between this plugin and coc.nvim + ccls

### ISSUE THREAD

**Issue by ssh352** [m-pilia/vim-ccls#37]
Thank you!

**Comment by m-pilia** [comment]
Hi @ssh352! The main purpose of this plugin is to add a tree viewer to visualise call/inheritance/type hierarchies (based on the $ccls/call, $ccls/member and $ccls/inheritance methods, that are not part of the standard LSP and therefore not supported out-of-the-box by most LSP client plugins). This plugin is not a replacement of coc.nvim, and can be used in combination with it (or with other LSP client plugins). You can find more information and a preview of the functionalities in the [README.md](https://github.com/m-pilia/vim-ccls/blob/master/README.md) and in the [documentation](https://github.com/m-pilia/vim-ccls/blob/master/doc/vim-ccls.txt).

**Comment by ssh352** [comment]
The call hierarchy is very useful thank you!
