### ISSUE TITLE
nvim_lsp changed its name, resulting in "No LSP plugin found!" in vim-ccls

### ISSUE THREAD

**Issue by vgeof** [m-pilia/vim-ccls#39]
Hello,
The package nvim-lsp changed its name into lspconfig a few days ago (https://github.com/neovim/nvim-lspconfig/commit/ddcd9e6aae50d6397e43e4fc9ba0cf7a82cc79de). So I get the message "No LSP plugin found" when trying to do a call hierarchy.

I found a quick workaround to be able to use call hierarchies again:

diff --git a/autoload/ccls/lsp.vim b/autoload/ccls/lsp.vim
index ff8d7c6..3a7b31c 100644
--- a/autoload/ccls/lsp.vim
+++ b/autoload/ccls/lsp.vim
@@ -95,7 +95,7 @@ function! ccls#lsp#request(bufnr, method, params, handler) abort
         catch
             call ccls#util#warning('LSP error')
         endtry
-    elseif get(g:, 'nvim_lsp', v:false)
+    elseif get(g:, 'lspconfig', v:false)
         " Use nvim-lsp
         let l:call_id = ccls#lsp#nvim_lsp#register(a:handler)
         let l:args = [a:bufnr, a:method, a:params, l:call_id]

**Comment by m-pilia** [comment]
Thanks @vgeof for the report. I will fix this soon.

**Comment by vgeof** [comment]
Thanks a lot !!!
