### ISSUE TITLE
Plugin suddenly stopped working

### ISSUE THREAD

**Issue by sserohin** [m-pilia/vim-ccls#53]
I use NVIM v0.6.0-dev.
I found that is capabilities of nvim-lspconfig whith ccls is not enaugh to manage big c++ project. And this plugin is very helpful.

When I trying to call CclsDerivedHierarchy, I get this error. 
`Error executing vim.schedule lua callback: /home/serhii/.vim/plugged/vim-ccls/lua/vim_ccls/init.lua:27: Vim(let):E716: Key not present in Dictionary: "location.uri)"`

maybe it is related to nvim update?  How to solve this issue?

Thanks

**Comment by m-pilia** [comment]
Hi @sserohin, thanks for reporting this issue!

I reproduced the problem. Neovim 0.6 will introduce some breaking changes to the built-in LSP API in this [recently merged PR](https://www.reddit.com/r/neovim/comments/pe07yg/psa_breaking_builtin_language_server_client_lsp/). Therefore I need to update `vim-ccls` to be compatible with neovim 0.6.

I added support for the new API in #54 that should fix the issue you are encountering.

**Comment by sserohin** [comment]
Thank you a lot!
