### ISSUE TITLE
[Bug] `ccls` not detected when starting other LSP in a different buffer

### ISSUE THREAD

**Issue by pidgeon777** [m-pilia/vim-ccls#61]
This line:

https://github.com/m-pilia/vim-ccls/blob/93ac5dbdeaaaed8fdfd6d850f1e57fb28d204886/lua/vim_ccls/init.lua#L7

Should be changed to:

```lua
for _, v in pairs(clients) do 
```

otherwise `ccls` won't be detected anymore for a given buffer, when starting another LSP server on a different buffer.

My modification has been tested and it always works. Some possible explanations:

https://github.com/ojroques/nvim-hardline/pull/31

https://www.tutorialspoint.com/what-is-the-difference-between-pairs-vs-ipairs-in-lua#:~:text=In%20Lua%2C%20we%20make%20use,stored%20at%20that%20index%20table.

**Comment by m-pilia** [comment]
Thank you @pidgeon777 for reporting this!

**Comment by pidgeon777** [comment]
It's been a pleasure, yours is a good plugin.

I also hope one day this will be taken into consideration:

https://github.com/m-pilia/vim-ccls/issues/62
