### ISSUE TITLE
<CR> overriden in Quickfix window

### ISSUE THREAD

**Issue by windrg** [m-pilia/vim-ccls#64]
Hi,
Whenever I hit Entery key in a quickfix window whatever it is local or global,
it tries to run CclsMemberHierachy. But I don't want to do this but want to do the original behavior - jump to the location where it indicates as intended.
Could you tell me how I get it, please?

**Comment by m-pilia** [comment]
Hi @windrg, `vim-ccls` should not set any mappings that call `CclsMemberHierachy`, and should not set any mappings in a quickfix buffer at all.

Please check where the mapping definition comes from by running this command inside a quickfix window where you observe the issue:
```
:verbose nmap <CR>
```

**Comment by windrg** [comment]
Thanks for your answer.
